smilies =   [["16", "16", "frown.gif", "Frown", ":("],
            ["16", "16", "mad.gif", "Mad", ":mad:"],
            ["16", "16", "tongue.gif", "Stick Out Tongue", ":p"],
            ["16", "16", "wink.gif", "Wink", ";)"],
            ["16", "16", "biggrin.gif", "Big Grin", ":D"],
            ["16", "16", "redface.gif", "Embarressment", ":o"],
            ["16", "16", "smile.gif", "Smile", ":)"],
            ["16", "16", "cool.gif", "Cool", ":cool:"],
            ["17", "18", "facepalm..gif", "Facepalm", ":facepalm:"],
            ["21", "16", "confused.gif", "Confused", ":confused:"],
            ["31", "65", "rtfm.gif", "rtfm!", ":rtfm:"],
            ["23", "22", "pimp.gif", "Pimp", ":pimp:"],
            ["28", "33", "mofo.gif", "Mofo", ":mofo:"],
            ["15", "29", "handsdown.gif", "Handsdown", ":handsdown:"],
            ["30", "20", "bandit.gif", "Bandit", ":bandit:"],
            ["16", "16", "rolleyes.gif", "Roll Eyes (Sarcastic)", ":rolleyes:"],
            ["16", "16", "eek.gif", "EEK!", ":eek:"],
            ["16", "16", "awesome.gif", "Awesome", ":awesome:"]
]

icons =   [["16", "16", "icon4.gif", "Exclamation"],
            ["16", "16", "mad.gif", "Mad", ":mad:"],
            ["16", "16", "tongue.gif", "Stick Out Tongue", ":p"],
            ["16", "16", "wink.gif", "Wink", ";)"],
            ["16", "16", "biggrin.gif", "Big Grin", ":D"],
            ["16", "16", "redface.gif", "Embarressment", ":o"],
            ["16", "16", "smile.gif", "Smile", ":)"],
            ["16", "16", "cool.gif", "Cool", ":cool:"],
            ["17", "18", "facepalm..gif", "Facepalm", ":facepalm:"],
            ["21", "16", "confused.gif", "Confused", ":confused:"],
            ["31", "65", "rtfm.gif", "rtfm!", ":rtfm:"],
            ["23", "22", "pimp.gif", "Pimp", ":pimp:"],
            ["28", "33", "mofo.gif", "Mofo", ":mofo:"],
            ["15", "29", "handsdown.gif", "Handsdown", ":handsdown:"],
            ["30", "20", "bandit.gif", "Bandit", ":bandit:"],
            ["16", "16", "rolleyes.gif", "Roll Eyes (Sarcastic)", ":rolleyes:"],
            ["16", "16", "eek.gif", "EEK!", ":eek:"],
            ["16", "16", "awesome.gif", "Awesome", ":awesome:"]
]
